[users]
joe = "example"
jane = "another"

[files]
include_default = true
# Won't be created, must exist already
directories = ["/Some/directory/somewhere", "/Some/directory/somewhere-else"]
# Won't be created - use `matchbox_webapp create` to create a blank
# template file with this filepath
changes_file = "/Full/path/to/file"
